name: Merge
on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 * * 1'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout latest code
        uses: actions/checkout@v3.0.2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-docs-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            update-docs-${{ runner.os }}-go-

      # We run tidy after download because download and tidy produce different go.sum.
      # See https://github.com/golang/go/issues/35832
      - name: Download dependencies
        run: go mod download && go mod tidy
        
      - name: Install golds
        run: go install go101.org/golds@latest

      - name: Generate files
        run: make generate

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v4.1.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'docs: update gotd docs to the latest version'
          branch: feat/update-docs
          delete-branch: true

          title: 'docs: update gotd docs to the latest version'
          labels: |
            dependencies
            
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
